# Generated by Django 4.2.27 on 2025-12-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на товар')),
                ('status', models.CharField(choices=[('cooling', 'Охлаждение'), ('ready', 'Можно покупать'), ('bought', 'Куплено'), ('cancelled', 'Передумал')], default='cooling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooling_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания охлаждения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
                'ordering': ['-created_at'],
            },
        ),
    ]
