# Generated by Django 4.2.27 on 2025-12-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='link_url',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего уведомления'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='notify_on_end',
            field=models.BooleanField(default=True, verbose_name='Уведомить по окончании'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='report_frequency',
            field=models.CharField(choices=[('none', 'Не напоминать'), ('daily', 'Каждый день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='weekly', max_length=20, verbose_name='Частота отчетов'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='cooling_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'ordering': ['-created_at'],
            },
        ),
    ]
