# Generated by Django 4.2.27 on 2025-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_remove_wishitem_image_url_remove_wishitem_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
