# Generated by Django 4.2.27 on 2025-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('nickname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Никнейм пользователя')),
                ('current_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущие накопления')),
                ('monthly_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сколько откладывает в месяц')),
                ('monthly_spendings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сколько тратит в месяц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
