# Generated by Django 4.2.27 on 2025-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blacklisted_categories',
            field=models.TextField(blank=True, default='', verbose_name='Черный список'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=20, verbose_name='Тема оформления'),
        ),
    ]
